### PR TITLE
Improvements for monit

### PR DESCRIPTION
**Pull request by bogdando**
* Lower daemon polling interval from 120 to 30 sec
* Add timeout for start/stop actions
* Add pidless services tracking as well
* Add params for Redhat/Centos support
* Make config template params based
* Add syslog support
* Redefine service's provider to monit, if already
  in catalog
* Adjust rspecs
* Add docs

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by bogdando** [comment]
Sorry, for a very late response. Will do

**Comment by jbussdieker** [comment]
Awesome! Thank you!

**Comment by bogdando** [comment]
now it should be mergable

**Comment by bogdando** [comment]
And now, it even passes rspecs! :)

**Comment by bogdando** [comment]
Hm, do you know why ruby 1.8.7 is failing rspecs? Looking into the logs https://travis-ci.org/jbussdieker/puppet-monit/jobs/72290121 I have no guesses.

**Comment by bogdando** [comment]
The rspecs seems failing with the 1.8.7 ruby at master branch as well. So this issue should not be related to the subject patch.

**Pull request merged**
